// <auto-generated />
namespace Shelfalytics.DbContext.Migrations.Main
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedMailOosQueue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedMailOosQueue));
        
        string IMigrationMetadata.Id
        {
            get { return "201709231731175_addedMailOosQueue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
